[package]
name = "tetrs"
version = "0.1.0"
authors = ["Simon Whitehead <chemnova@gmail.com>"]

[dependencies]
piston_window = "*"
pistoncore-sdl2_window = "*"
piston2d-opengl_graphics = "*"
gfx_device_gl = "*"
rand = "*"
find_folder = "*"